config/routes.rb
Myrottenpotatoes::Application.routes.draw do
  get 'movies_:sort' => 'movies#index', :as => 'sort_movies'
  resources :movies
  root :to => redirect('/movies')

  get 'login' => 'sessions#login'
  get 'auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'auth/failure' => 'sessions#failure'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date
  def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
  validates :title, :presence => true
  validates :release_date, :presence => true
  validate :released_1930_or_later # uses custom validator below
  validates :rating, :inclusion => {:in => Movie.all_ratings},
    :unless => :grandfathered?
  def released_1930_or_later
    errors.add(:release_date, 'must be 1930 or later') if
      release_date && release_date < Date.parse('1 Jan 1930')
  end
  @@grandfathered_date = Date.parse('1 Nov 1968')
  def grandfathered?
    release_date && release_date >= @@grandfathered_date
  end
end

app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
  attr_protected :uid, :provider, :name # see text for explanation
  def self.create_with_omniauth(auth)
    Moviegoer.create!(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_current_user
  protected # prevents method from being invoked by a route
  def set_current_user
    # we exploit the fact that find_by_id(nil) returns nil
    @current_user ||= Moviegoer.find_by_id(session[:user_id])
    redirect_to login_path and return unless @current_user
  end
end

app/controllers/movies_controller.rb
# This file is app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:sort] == "title" then 
      @movies = Movie.order("title") #Project 4.3.3
    elsif params[:sort] == "rating" then
      @movies = Movie.order("rating")
    elsif params[:sort] == "date" then
      @movies = Movie.order("release_date")
    else
      @movies = Movie.all
    end
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.html.haml by default
  end

#  def new
    # default: render 'new' template
#  end

#  def create
#    @movie = Movie.create!(params[:movie])
#    flash[:notice] = "#{@movie.title} was successfully created."
#    redirect_to movies_path
#  end

  def edit
    @movie = Movie.find params[:id]
  end

#  def update
#    @movie = Movie.find params[:id]
#    @movie.update_attributes!(params[:movie])
#    flash[:notice] = "#{@movie.title} was successfully updated."
    #redirect_to movie_path(@movie)
#    respond_to do |client_wants|
#      client_wants.html {  redirect_to movie_path(@movie)  } # as before
#      client_wants.xml  {  render :xml => @movie.to_xml    }
#    end
#  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end
  # replaces the 'create' method in controller:
  def create
    @movie = Movie.new(params[:movie])
    if @movie.save
      flash[:notice] = "#{@movie.title} was successfully created."
      redirect_to movies_path
    else
      render 'new' # note, 'new' template can access @movie's field values!
    end
  end
  # replaces the 'update' method in controller:
  def update
    @movie = Movie.find params[:id]
    if @movie.update_attributes(params[:movie])
      flash[:notice] = "#{@movie.title} was successfully updated."
      redirect_to movie_path(@movie)
    else
      render 'edit' # note, 'edit' template can access @movie's field values!
    end
  end
  # as a reminder, here is the original 'new' method:
  def new
    @movie = Movie.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # user shouldn't have to be logged in before logging in!
  skip_before_filter :set_current_user
  def create
    auth=request.env["omniauth.auth"]
    user=Moviegoer.find_by_provider_and_uid(auth["provider"],auth["uid"]) ||
      Moviegoer.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to movies_path
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged out successfully.'
    redirect_to movies_path
  end
  def login

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render :partial => 'sessions/login'
    -# this goes just inside %body:
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    = yield

app/views/movies/edit.html.haml
%h2 Edit Movie

- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :description, 'Description' #Project 4.7
  = text_area :movie, 'description'

  %br

  = submit_tag 'Save Changes'
  -#= link_to 'Cancel', movies_path 
  -#Project 4.4
  = link_to 'Cancel', movie_path(@movie) 
  -#Project 4.5

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th= link_to "Movie Title", sort_movies_path("title")
      -#%th Movie Title
      %th= link_to "Rating", sort_movies_path("rating")
      -#%th Rating
      %th= link_to "Release Date", sort_movies_path("date")
      -#%th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h2 Create New Movie

- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error

= form_tag movies_path, :method => :post do

  = label :movie, :title, 'Title'
  = text_field :movie, :title

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :description, 'Description' #Project 4.7
  = text_area :movie, 'description'

  %br

  = submit_tag 'Save Changes'
  = link_to 'Cancel', movies_path #Project 4.4

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)

%br

= link_to 'Delete', movie_path(@movie), :method => :delete

%br

= link_to 'Back to movie list', movies_path